### ISSUE TITLE
Add C Hessian example

### ISSUE THREAD

**Issue by martinjm97** [EnzymeAD/Enzyme#1123]
Credit (blame) to Billy

https://fwd.gymni.ch/PaQUnB

```julia
using Enzyme
using Base.Experimental: @aliasscope, Const

using BenchmarkTools

using StaticArrays
Enzyme.API.inlineall!(true)
Enzyme.API.printall!(true)

function f(pos)
    e = 0.
    n = length(pos)
    @inbounds for i in 1:3:n
        vx, vy, vz = pos[ i ], pos[i+1 ], pos[i+2 ]
        wx, wy, wz = pos[ (i+3 - 1) % n + 1 ], pos[(i+4 - 1) % n + 1 ], pos[ (i+5 - 1) % n + 1]
        e += (wx-vx)^2 + (wy-vy)^2 + (wz-vz)^2
    end
    return e
end

function gradient_ip(in_t, out)
    @aliasscope let in = Const(in)
        Enzyme.autodiff_deferred(Reverse, f, Duplicated(in, out))
    end
    return
end

function hess_row_ip(in, idx)

    onehot = similar(in)
    onehot .= 0.0
    onehot[idx] = 1.0

    undef = similar(in)
    undef .= 0.0
    
    # can reuse
    out = similar(in)
    out .= 0.0
    
    Enzyme.autodiff(Forward, gradient_ip, Const, Duplicated(in, onehot), DuplicatedNoNeed(out, undef))
    return undef
end

function test(Type, n)
    in = Type([p for i in 1:n for p in [cos(2π*i/n), sin(2π*i/n), 0]])

    f(in)

    # outs = []
    # for i in 1:length(in)
    #     push!(outs, hess_row_ip(in, i))
    # end


    identity = []
    outputs = []
    for idx in 1:length(in)
        onehot = similar(in)
        onehot .= 0.0
        onehot[idx] = 1.0
        push!(identity, onehot)
        undef = similar(in)
        undef .= 0.0
        push!(outputs, undef)
    end

    bd_in = BatchDuplicated(in, (identity..., ))
    out_tmp = similar(in)
    out_tmp .= 0.0
    bd_out = BatchDuplicatedNoNeed(out_tmp, (outputs...,))

    Enzyme.autodiff(
        Forward, 
        gradient_ip, Const, bd_in, bd_out)

    @show Type, n
    @btime Enzyme.autodiff(
            Forward, 
            gradient_ip, Const, $bd_in, $bd_out)
end

for n in (3, 30, 300)
    # test(MVector{3*n, Float64}, n)
    test(Vector{Float64}, n)
end
```

**Comment by jeffpollock9** [comment]
@martinjm97 thanks for adding these examples, the hessian C++ code really helped me. However if I run your example with clang's address sanitizer (`-O2 -fno-omit-frame-pointer -fsanitize=address`) and change the main to e.g.:
```c++
int main() {
    run<8>(800);
}
```
I noticed we get:
```
=================================================================
==27156==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7b8ec50ff800 at pc 0x562d5038b927 bp 0x7ffd2f5d3720 sp 0x7ffd2f5d3718
READ of size 8 at 0x7b8ec50ff800 thread T0
    #0 0x562d5038b926 in f(double*, unsigned long) /tmp/compiler-explorer-compiler2025103-105-1m1c11n.qswv/example.cpp:15:21
    #1 0x562d5038b926 in gradient_ip(double*, double*, unsigned long) /tmp/compiler-explorer-compiler2025103-105-1m1c11n.qswv/example.cpp:26:5
    #2 0x562d5038b926 in void hessian<8ul>(double*, double*, double*, double*, unsigned long) /tmp/compiler-explorer-compiler2025103-105-1m1c11n.qswv/example.cpp:38:9
    #3 0x562d5038b926 in void run<8ul>(unsigned long) /tmp/compiler-explorer-compiler2025103-105-1m1c11n.qswv/example.cpp:81:5
    #4 0x562d5038a00d in main /tmp/compiler-explorer-compiler2025103-105-1m1c11n.qswv/example.cpp:102:5
    #5 0x7f8ec8205d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: cd410b710f0f094c6832edd95931006d883af48e)
    #6 0x7f8ec8205e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: cd410b710f0f094c6832edd95931006d883af48e)
    #7 0x562d502a03a4 in _start (/tmp/compiler-explorer-compiler2025103-105-1m1c11n.qswv/output.s+0x2d3a4)

0x7b8ec50ff800 is located 0 bytes after 5120000-byte region [0x7b8ec4c1d800,0x7b8ec50ff800)
allocated by thread T0 here:
    #0 0x562d5038896d in operator new[](unsigned long) /root/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:111:37
    #1 0x562d5038a146 in void run<8ul>(unsigned long) /tmp/compiler-explorer-compiler2025103-105-1m1c11n.qswv/example.cpp:59:24
    #2 0x562d5038a00d in main /tmp/compiler-explorer-compiler2025103-105-1m1c11n.qswv/example.cpp:102:5
    #3 0x7f8ec8205d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: cd410b710f0f094c6832edd95931006d883af48e)

SUMMARY: AddressSanitizer: heap-buffer-overflow /tmp/compiler-explorer-compiler2025103-105-1m1c11n.qswv/example.cpp:15:21 in f(double*, unsigned long)
Shadow bytes around the buggy address:
  0x7b8ec50ff580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7b8ec50ff600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7b8ec50ff680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7b8ec50ff700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7b8ec50ff780: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7b8ec50ff800:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7b8ec50ff880: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7b8ec50ff900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7b8ec50ff980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7b8ec50ffa00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7b8ec50ffa80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==27156==ABORTING
```
here is a link: https://fwd.gymni.ch/pn1NXw

In fact many combinations of `width` and `n` seem to (randomly to me) not work e.g. `run<4>(40)`.

If you (or anyone reading) has any ideas regarding what's going on and how to fix, it would be great. Thanks!
