### ISSUE TITLE
Asan reports `stack-use-after-scope`

### ISSUE THREAD

**Issue by dime10** [EnzymeAD/Enzyme#1460]
Hi, I just thought I would report a `stack-use-after-scope` issue discovered while building Enzyme with address sanitization.

Built on commit: 8d22ed1b8c424a061ed9d6d0baf0cc0d2d6842e2

This is the output (abbreviated):
```
==148875==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffdb6e3ec20 at pc 0x7efda0fc17ab bp 0x7ffdb6e3cb20 sp 0x7ffdb6e3cb10
READ of size 8 at 0x7ffdb6e3ec20 thread T0
    #0 0x7efda0fc17aa in DifferentialUseAnalysis::minCut(llvm::DataLayout const&, llvm::LoopInfo&, llvm::SmallPtrSetImpl<llvm::Value*> const&, llvm::SmallPtrSetImpl<llvm::Value*> const&, llvm::SmallPtrSetImpl<llvm::Value*>&, llvm::SmallPtrSetImpl<llvm::Value*>&, llvm::ValueMap<llvm::Value*, GradientUtils::Rematerializer, llvm::ValueMapConfig<llvm::Value*, llvm::sys::SmartMutex<false> > > const&, llvm::TargetLibraryInfo&)
    #1 0x7efda0bc8c2a in GradientUtils::computeMinCache()
    #2 0x7efda05e32cb in EnzymeLogic::CreatePrimalAndGradient(ReverseCacheKey const&&, TypeAnalysis&, AugmentedReturn const*, bool)
    #3 0x7efda010ab13 in (anonymous namespace)::EnzymeBase::HandleAutoDiff(llvm::Instruction*, unsigned int, llvm::Value*, llvm::Type*, llvm::SmallVectorImpl<llvm::Value*>&, std::map<int, llvm::Type*, std::less<int>, std::allocator<std::pair<int const, llvm::Type*> > > const&, std::vector<DIFFE_TYPE, std::allocator<DIFFE_TYPE> > const&, llvm::Function*, DerivativeMode, (anonymous namespace)::EnzymeBase::Options&, bool)
    #4 0x7efda011240d in (anonymous namespace)::EnzymeBase::HandleAutoDiffArguments(llvm::CallInst*, DerivativeMode, bool)
    #5 0x7efda011f32f in (anonymous namespace)::EnzymeBase::lowerEnzymeCalls(llvm::Function&, std::set<llvm::Function*, std::less<llvm::Function*>, std::allocator<llvm::Function*> >&)
    #6 0x7efda012e0dd in (anonymous namespace)::EnzymeBase::run(llvm::Module&)
    #7 0x7efda01364a7 in llvm::detail::PassModel<llvm::Module, EnzymeNewPM, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&)
    ...
    
Address 0x7ffdb6e3ec20 is located in stack of thread T0 at offset 8064 in frame
    #0 0x7efda0fb5e0f in DifferentialUseAnalysis::minCut(llvm::DataLayout const&, llvm::LoopInfo&, llvm::SmallPtrSetImpl<llvm::Value*> const&, llvm::SmallPtrSetImpl<llvm::Value*> const&, llvm::SmallPtrSetImpl<llvm::Value*>&, llvm::SmallPtrSetImpl<llvm::Value*>&, llvm::ValueMap<llvm::Value*, GradientUtils::Rematerializer, llvm::ValueMapConfig<llvm::Value*, llvm::sys::SmartMutex<false> > > const&, llvm::TargetLibraryInfo&)

  This frame has 238 object(s):
    [48, 49) '<unknown>'
    [64, 65) '<unknown>'
    [80, 81) '<unknown>'
    [96, 97) '<unknown>'
    [112, 113) '<unknown>'
    [128, 129) '<unknown>'
    [144, 145) '<unknown>'
    [160, 161) '<unknown>'
    [176, 177) '<unknown>'
    [192, 193) '<unknown>'
    [208, 209) '<unknown>'
    [224, 225) '<unknown>'
    [240, 241) '<unknown>'
    [256, 257) '<unknown>'
    [272, 273) '<unknown>'
    [288, 289) '<unknown>'
    [304, 305) '<unknown>'
    [320, 321) '<unknown>'
    [336, 337) '<unknown>'
    [352, 353) '<unknown>'
    [368, 369) '<unknown>'
    [384, 385) '<unknown>'
    [400, 401) '<unknown>'
    [416, 417) '<unknown>'
    [432, 433) '<unknown>'
    [448, 449) '<unknown>'
    [464, 465) '<unknown>'
    [480, 481) '<unknown>'
    [496, 497) '<unknown>'
    [512, 513) '<unknown>'
    [528, 529) '<unknown>'
    [544, 545) '<unknown>'
    [560, 561) '<unknown>'
    [576, 577) '<unknown>'
    [592, 593) '<unknown>'
    [608, 609) '<unknown>'
    [624, 625) '<unknown>'
    [640, 641) '__map_alloc'
    [656, 664) '__for_begin' (line 541)
    [688, 696) '__for_end' (line 541)
    [720, 728) '<unknown>'
    [752, 760) '<unknown>'
    [784, 792) '<unknown>'
    [816, 824) '<unknown>'
    [848, 856) '<unknown>'
    [880, 888) '__for_begin' (line 618)
    [912, 920) '__for_end' (line 618)
    [944, 952) '<unknown>'
    [976, 984) '<unknown>'
    [1008, 1016) '__for_begin' (line 620)
    [1040, 1048) '__for_end' (line 620)
    [1072, 1080) '<unknown>'
    [1104, 1112) '<unknown>'
    [1136, 1144) 'found' (line 635)
    [1168, 1176) '<unknown>'
    [1200, 1208) '<unknown>'
    [1232, 1240) '<unknown>'
    [1264, 1272) '<unknown>'
    [1296, 1304) '<unknown>'
    [1328, 1336) '<unknown>'
    [1360, 1368) '<unknown>'
    [1392, 1400) '<unknown>'
    [1424, 1432) '<unknown>'
    [1456, 1464) '<unknown>'
    [1488, 1496) '<unknown>'
    [1520, 1528) '<unknown>'
    [1552, 1560) '<unknown>'
    [1584, 1592) '<unknown>'
    [1616, 1624) '<unknown>'
    [1648, 1656) '<unknown>'
    [1680, 1688) '<unknown>'
    [1712, 1720) '<unknown>'
    [1744, 1752) '<unknown>'
    [1776, 1784) '<unknown>'
    [1808, 1816) '<unknown>'
    [1840, 1848) '<unknown>'
    [1872, 1880) '<unknown>'
    [1904, 1912) '<unknown>'
    [1936, 1944) '<unknown>'
    [1968, 1976) '<unknown>'
    [2000, 2008) '__an'
    [2032, 2040) '<unknown>'
    [2064, 2072) '<unknown>'
    [2096, 2104) '<unknown>'
    [2128, 2136) '__i'
    [2160, 2168) '<unknown>'
    [2192, 2200) '<unknown>'
    [2224, 2232) '<unknown>'
    [2256, 2264) '<unknown>'
    [2288, 2296) '<unknown>'
    [2320, 2328) '__an'
    [2352, 2360) '<unknown>'
    [2384, 2392) '<unknown>'
    [2416, 2424) '<unknown>'
    [2448, 2456) '__i'
    [2480, 2488) '<unknown>'
    [2512, 2520) '<unknown>'
    [2544, 2552) '<unknown>'
    [2576, 2584) '<unknown>'
    [2608, 2616) '<unknown>'
    [2640, 2648) '__an'
    [2672, 2680) '<unknown>'
    [2704, 2712) '<unknown>'
    [2736, 2744) '<unknown>'
    [2768, 2776) '__an'
    [2800, 2808) '<unknown>'
    [2832, 2840) '<unknown>'
    [2864, 2872) '<unknown>'
    [2896, 2904) '__an'
    [2928, 2936) '<unknown>'
    [2960, 2968) '<unknown>'
    [2992, 3000) '<unknown>'
    [3024, 3032) '<unknown>'
    [3056, 3064) '<unknown>'
    [3088, 3096) '<unknown>'
    [3120, 3128) '__i'
    [3152, 3160) '<unknown>'
    [3184, 3192) '<unknown>'
    [3216, 3224) '<unknown>'
    [3248, 3256) '<unknown>'
    [3280, 3288) '<unknown>'
    [3312, 3320) '<unknown>'
    [3344, 3352) '<unknown>'
    [3376, 3384) '<unknown>'
    [3408, 3416) '__i'
    [3440, 3448) '<unknown>'
    [3472, 3480) '<unknown>'
    [3504, 3512) '<unknown>'
    [3536, 3544) '<unknown>'
    [3568, 3576) '<unknown>'
    [3600, 3608) '__i'
    [3632, 3640) '<unknown>'
    [3664, 3672) '<unknown>'
    [3696, 3704) '<unknown>'
    [3728, 3736) '<unknown>'
    [3760, 3768) '<unknown>'
    [3792, 3800) '<unknown>'
    [3824, 3832) '__i'
    [3856, 3864) '<unknown>'
    [3888, 3896) '<unknown>'
    [3920, 3928) '<unknown>'
    [3952, 3960) '<unknown>'
    [3984, 3992) '<unknown>'
    [4016, 4024) '<unknown>'
    [4048, 4056) '__an'
    [4080, 4088) '<unknown>'
    [4112, 4120) '<unknown>'
    [4144, 4152) '<unknown>'
    [4176, 4192) '<unknown>'
    [4208, 4224) '<unknown>'
    [4240, 4256) '<unknown>'
    [4272, 4288) '<unknown>'
    [4304, 4320) '<unknown>'
    [4336, 4352) '<unknown>'
    [4368, 4384) '<unknown>'
    [4400, 4416) '<unknown>'
    [4432, 4448) '<unknown>'
    [4464, 4480) '<unknown>'
    [4496, 4512) 'end' (line 585)
    [4528, 4544) '<unknown>'
    [4560, 4576) '<unknown>'
    [4592, 4608) 'v' (line 596)
    [4624, 4640) 'u' (line 599)
    [4656, 4672) 'N' (line 620)
    [4688, 4704) '<unknown>'
    [4720, 4736) '<unknown>'
    [4752, 4768) '<unknown>'
    [4784, 4800) '<unknown>'
    [4816, 4832) '__p'
    [4848, 4864) '<unknown>'
    [4880, 4896) '<unknown>'
    [4912, 4928) '<unknown>'
    [4944, 4960) 'Result'
    [4976, 4992) '__p'
    [5008, 5024) '<unknown>'
    [5040, 5056) '<unknown>'
    [5072, 5088) '<unknown>'
    [5104, 5120) '__p'
    [5136, 5152) '<unknown>'
    [5168, 5184) '<unknown>'
    [5200, 5216) '<unknown>'
    [5232, 5248) 'Result'
    [5264, 5280) '__p'
    [5296, 5312) '<unknown>'
    [5328, 5344) '<unknown>'
    [5360, 5376) '<unknown>'
    [5392, 5408) '__p'
    [5424, 5440) '<unknown>'
    [5456, 5472) '<unknown>'
    [5488, 5504) '<unknown>'
    [5520, 5536) '__p'
    [5552, 5568) '<unknown>'
    [5584, 5600) '__p'
    [5616, 5632) '<unknown>'
    [5648, 5664) '<unknown>'
    [5680, 5696) 'p'
    [5712, 5728) '<unknown>'
    [5744, 5760) '<unknown>'
    [5776, 5792) '<unknown>'
    [5808, 5824) '<unknown>'
    [5840, 5856) '<unknown>'
    [5872, 5888) '<unknown>'
    [5904, 5920) '<unknown>'
    [5936, 5952) '<unknown>'
    [5968, 5984) '<unknown>'
    [6000, 6032) '__for_begin' (line 539)
    [6064, 6096) '__for_end' (line 539)
    [6128, 6160) '__for_begin' (line 543)
    [6192, 6224) '__for_end' (line 543)
    [6256, 6288) '__for_begin' (line 556)
    [6320, 6352) '__for_end' (line 556)
    [6384, 6416) '__for_begin' (line 572)
    [6448, 6480) '__for_end' (line 572)
    [6512, 6544) '__for_begin' (line 575)
    [6576, 6608) '__for_end' (line 575)
    [6640, 6672) '__for_begin' (line 586)
    [6704, 6736) '__for_end' (line 586)
    [6768, 6800) '<unknown>'
    [6832, 6864) '<unknown>'
    [6896, 6928) '<unknown>'
    [6960, 6992) '<unknown>'
    [7024, 7056) '<unknown>'
    [7088, 7120) '__first' (line 530)
    [7152, 7184) '__last' (line 530)
    [7216, 7248) '<unknown>'
    [7280, 7312) '<unknown>'
    [7344, 7376) '<unknown>'
    [7408, 7448) '<unknown>'
    [7488, 7528) '<unknown>'
    [7568, 7608) 'Empty'
    [7648, 7688) 'Tombstone'
    [7728, 7768) 'Empty'
    [7808, 7848) 'Tombstone'
    [7888, 7936) 'G' (line 538)
    [7968, 8016) 'Orig' (line 579)
    [8048, 8096) 'parent' (line 583) <== Memory access at offset 8064 is inside this variable
    [8128, 8176) 'parent' (line 613)
    [8208, 8288) 'todo' (line 631)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope in DifferentialUseAnalysis::minCut(llvm::DataLayout const&, llvm::LoopInfo&, llvm::SmallPtrSetImpl<llvm::Value*> const&, llvm::SmallPtrSetImpl<llvm::Value*> const&, llvm::SmallPtrSetImpl<llvm::Value*>&, llvm::SmallPtrSetImpl<llvm::Value*>&, llvm::ValueMap<llvm::Value*, GradientUtils::Rematerializer, llvm::ValueMapConfig<llvm::Value*, llvm::sys::SmartMutex<false> > > const&, llvm::TargetLibraryInfo&)
...
==148875==ABORTING
```

**Comment by wsmoses** [comment]
bumping @dime10 for the reproducer?

**Comment by dime10** [comment]
Hi @wsmoses, apologies for taking a while to get back to your question. I didn't have an easily reproducible test case on hand because enzyme is deeply integrated into our own compiler package.

I managed to distill something down to the following though. It seems related to the use of the custom allocation/free functions, since without them the error is not raised:
```ll
; ModuleID = 'LLVMDialectModule'
source_filename = "LLVMDialectModule"

@enzyme_dupnoneed = linkonce constant i8 0
@enzyme_const = linkonce constant i8 0
@__enzyme_function_like_free = local_unnamed_addr global [2 x ptr] [ptr @_mlir_memref_to_llvm_free, ptr @freename]
@freename = linkonce constant [5 x i8] c"free\00"
@dealloc_indices = linkonce constant [3 x i8] c"-1\00"
@__enzyme_allocation_like = local_unnamed_addr global [4 x ptr] [ptr @_mlir_memref_to_llvm_alloc, ptr null, ptr @dealloc_indices, ptr @_mlir_memref_to_llvm_free]

declare void @__enzyme_autodiff0(...) local_unnamed_addr

declare void @_mlir_memref_to_llvm_free(ptr)

declare ptr @_mlir_memref_to_llvm_alloc(i64)

define { ptr, ptr, i64 } @jit_compiled(ptr %0, ptr %1, i64 %2, ptr %3, ptr %4, i64 %5) local_unnamed_addr {
  %7 = tail call ptr @_mlir_memref_to_llvm_alloc(i64 72)
  %8 = ptrtoint ptr %7 to i64
  %9 = add i64 %8, 63
  %10 = and i64 %9, -64
  %11 = inttoptr i64 %10 to ptr
  store double 0.000000e+00, ptr %11, align 64
  %12 = tail call ptr @_mlir_memref_to_llvm_alloc(i64 72)
  %13 = ptrtoint ptr %12 to i64
  %14 = add i64 %13, 63
  %15 = and i64 %14, -64
  %16 = inttoptr i64 %15 to ptr
  %17 = load i64, ptr %11, align 64
  store i64 %17, ptr %16, align 64
  tail call void @_mlir_memref_to_llvm_free(ptr %7)
  store double 1.000000e+00, ptr %16, align 64
  %18 = tail call ptr @_mlir_memref_to_llvm_alloc(i64 8)
  %19 = tail call ptr @_mlir_memref_to_llvm_alloc(i64 8)
  %20 = tail call ptr @_mlir_memref_to_llvm_alloc(i64 8)
  %21 = load i64, ptr %16, align 64
  store i64 %21, ptr %20, align 1
  tail call void @_mlir_memref_to_llvm_free(ptr %12)
  store i64 0, ptr %18, align 1
  tail call void (...) @__enzyme_autodiff0(ptr nonnull @f_compiled.preprocess, ptr nonnull @enzyme_const, ptr %0, ptr %1, ptr nonnull %18, i64 %2, ptr nonnull @enzyme_const, ptr %3, ptr nonnull @enzyme_const, ptr %4, i64 %5, ptr nonnull @enzyme_const, i64 1, ptr nonnull @enzyme_const, ptr %19, ptr nonnull @enzyme_dupnoneed, ptr %19, ptr nonnull %20, i64 0)
  tail call void @_mlir_memref_to_llvm_free(ptr nonnull %20)
  tail call void @_mlir_memref_to_llvm_free(ptr %19)
  %22 = icmp eq ptr %18, inttoptr (i64 3735928559 to ptr)
  br i1 %22, label %23, label %26

23:                                               ; preds = %6
  %24 = tail call ptr @_mlir_memref_to_llvm_alloc(i64 8)
  %25 = load i64, ptr inttoptr (i64 3735928559 to ptr), align 1
  store i64 %25, ptr %24, align 1
  br label %26

26:                                               ; preds = %23, %6
  %.pn3 = phi ptr [ %24, %23 ], [ %18, %6 ]
  %.pn2 = insertvalue { ptr, ptr, i64 } undef, ptr %.pn3, 0
  %.pn = insertvalue { ptr, ptr, i64 } %.pn2, ptr %.pn3, 1
  %27 = insertvalue { ptr, ptr, i64 } %.pn, i64 0, 2
  ret { ptr, ptr, i64 } %27
}

define void @f_compiled.preprocess(ptr %0, ptr %1, i64 %2, ptr %3, ptr %4, i64 %5, i64 %6, ptr nocapture readnone %7, ptr nocapture writeonly %8, i64 %9) {
  %.idx = shl i64 %6, 3
  %11 = tail call ptr @_mlir_memref_to_llvm_alloc(i64 %.idx)
  %12 = load double, ptr %4, align 8
  %13 = fcmp ogt double %12, 1.500000e+00
  %14 = load double, ptr %1, align 8
  %15 = fmul double %14, 2.000000e+00
  %storemerge = select i1 %13, double %15, double %14
  store double %storemerge, ptr %11, align 8
  %16 = alloca { ptr, ptr, i64 }, align 8
  store ptr %0, ptr %16, align 8
  %.repack2 = getelementptr inbounds { ptr, ptr, i64 }, ptr %16, i64 0, i32 1
  store ptr %1, ptr %.repack2, align 8
  %.repack4 = getelementptr inbounds { ptr, ptr, i64 }, ptr %16, i64 0, i32 2
  store i64 %2, ptr %.repack4, align 8
  %17 = alloca { ptr, ptr, i64 }, align 8
  store ptr %3, ptr %17, align 8
  %.repack6 = getelementptr inbounds { ptr, ptr, i64 }, ptr %17, i64 0, i32 1
  store ptr %4, ptr %.repack6, align 8
  %.repack8 = getelementptr inbounds { ptr, ptr, i64 }, ptr %17, i64 0, i32 2
  store i64 %5, ptr %.repack8, align 8
  %18 = alloca { ptr, ptr, i64, [1 x i64], [1 x i64] }, align 8
  store ptr %11, ptr %18, align 8
  %.repack10 = getelementptr inbounds { ptr, ptr, i64, [1 x i64], [1 x i64] }, ptr %18, i64 0, i32 1
  store ptr %11, ptr %.repack10, align 8
  %.repack12 = getelementptr inbounds { ptr, ptr, i64, [1 x i64], [1 x i64] }, ptr %18, i64 0, i32 2
  store i64 0, ptr %.repack12, align 8
  %.repack14 = getelementptr inbounds { ptr, ptr, i64, [1 x i64], [1 x i64] }, ptr %18, i64 0, i32 3
  store i64 %6, ptr %.repack14, align 8
  %.repack16 = getelementptr inbounds { ptr, ptr, i64, [1 x i64], [1 x i64] }, ptr %18, i64 0, i32 4
  store i64 1, ptr %.repack16, align 8
  %19 = tail call ptr @_mlir_memref_to_llvm_alloc(i64 8)
  %20 = alloca { ptr, ptr, i64 }, align 8
  store ptr %19, ptr %20, align 8
  %.repack18 = getelementptr inbounds { ptr, ptr, i64 }, ptr %20, i64 0, i32 1
  store ptr %19, ptr %.repack18, align 8
  %.repack20 = getelementptr inbounds { ptr, ptr, i64 }, ptr %20, i64 0, i32 2
  store i64 0, ptr %.repack20, align 8
  ;call void @f_compiled...
  %21 = load double, ptr %19, align 8
  store double %21, ptr %8, align 8
  ret void
}
```


Invoked with:
```sh
LD_PRELOAD=$(clang -print-file-name=libclang_rt.asan-x86_64.so) opt -load-pass-plugin=<LLVMEnzyme-18.so> <test_file.ll> -S -passes=enzyme`
```

And I compiled Enzyme with (LLVM compiled w/o asan):
```cmake
add_compile_options(-fsanitize=address)
add_link_options(-fsanitize=address)
```

**Comment by dime10** [comment]
Bumping this for a label update at least, I understand that the issue itself might not be the highest priority.

**Comment by wsmoses** [comment]
Ah I'm sorry I haven't had a chance to reproduce/investigate this yet.

However if you're able to get the asan trace on the current Enzyme main with debug info that would be helpful (as the code there has changed a lot since then)

**Comment by wsmoses** [comment]
Okay I have isolated the issue, and now turned into an assertion. Working on a fix.

**Comment by wsmoses** [comment]
@dime10 this will be fixed by https://github.com/EnzymeAD/Enzyme/pull/1700

While I was at it I also added native support for the mlir alloc/free functions, so you don't need to have those done via the global/metadata.

**Comment by dime10** [comment]
Hey @wsmoses, thanks a lot for providing that fix, appreciate it! The builtin recognition of custom malloc/free functions is also a nice touch.
