### ISSUE TITLE
Enzyme derivatives attempting to free stack allocations

### ISSUE THREAD

**Issue by RasmitDevkota** [EnzymeAD/Enzyme#2029]
I am using Enzyme in C to autodifferentiate computations spread across multiple functions, and there seems to be some sort of optimization or Enzyme behavior which is freeing memory allocated from the stack. The array is allocated with `alloca` as shown below in one of the Enzyme `diffeX` methods.
```llvm
invertif.end97:                                   ; preds = %remat_enter
  %"vla147'mi45" = alloca [32 x i8], align 16, !dbg !11863
  ...
```

However, it is then freed at a later point as shown below.
```llvm
  call void @free(ptr nonnull %"vla147'mi45"), !dbg !118
```
The exact location of the `free` instruction depends on the optimization level of the individual files - for example, O1 and O3 cause it to be freed at the end of the block in the same function, while O2 causes it to be freed before the end of the block but in another function to which the array pointer is passed.

This issue occurs during the compilation process, and only becomes apparent during runtime when an error such as `double free` or `mmap_chunk` occurs. The exact error which occurs differs from compile to compile, but not from run to run for a single compile. Regardless, the GDB trace always ends at a `free` instruction.

Interestingly, this only occurs for stack-allocated memory which is used as a return buffer to pass to a function to place its output into - it does not seem to occur for other arrays which contain input data, though I can't tell whether this is always the case. I have noticed similar behavior with other independent routines, with different structures spanning across different files, but still using this method of return buffer.

Because of confidentiality policies, I cannot post the original C code or Makefile, but I have simplified the Makefile, shown below.
```makefile
CC = clang
CFLAGS  = -Wall -Wno-unused-command-line-argument -fPIC -O1 -g -fsave-optimization-record -fno-discard-value-names -flto

ENZLLD   = ${HOME}/Enzyme/enzyme/build/Enzyme/LLDEnzyme-18.so
ENZLLVM  = ${HOME}/Enzyme/enzyme/build/Enzyme/LLVMEnzyme-18.so
ENZCLANG = ${HOME}/Enzyme/enzyme/build/Enzyme/ClangEnzyme-18.so
ENZFLAGS = -S -emit-llvm

debug: target1.ll target2.ll
        llvm-link target1.ll target2.ll -S -o debug_in.ll
        opt debug_in.ll -o debug_out.ll -S -load-pass-plugin=$(ENZLLVM) -passes=enzyme -enzyme-print-activity
        opt debug_out.ll -o debug_opt.ll -S -O1
        $(CC) -shared -fPIC debug_opt.ll -o libDebug.so -O0

target1.ll : file1.c file1.h file2.c file2.h
        $(CC) $(CFLAGS) -c file1.c $(ENZFLAGS) -o target1.ll

target2.ll : file3.c file3.h
        $(CC) $(CFLAGS) -c file3.c $(ENZFLAGS) -o target2.ll
```

The IR output above comes from `debug_opt.ll` and does not appear to occur in `debug_out.ll`, but I have notticed there are `vla147_malloccache` variables being created within Enzyme-generated methods after the first `opt`. I have purposefully forced `-O0` for the final shared object creation, but the issue seems to originate from the optimization flags used for the individual targets and the second `opt`. Setting `-O0` in those cases seems to prevent the error. So, although the issue doesn't seem to be occurring _during_ the Enzyme pass, it occurs _only within_ the Enzyme-generated methods, so I'm not sure if there's something in the generated code which is signalling `opt` in the second step to try and free the memory (maybe related to the `_malloccache` variables?). I searched the output from the `-fsave-optimization-record` and `-enzyme-print-activity` flags to see if there was any mention of this decision to insert a `free` instruction but I could not find anything like that in either.

I am trying to reproduce this issue from an independent code, but have been unsuccessful thus far. Although the source code cannot be shared, we may be able to provide additional output if any would be helpful in figuring this out!

**Comment by wsmoses** [comment]
Okay that's definitely bad/a bug (presumably in enzyme stack lowering).

Can you upload the IR of relevance?

**Comment by wsmoses** [comment]
[if per confidentiality policies, you can email it to me directly]

**Comment by RasmitDevkota** [comment]
> Okay that's definitely bad/a bug (presumably in enzyme stack lowering).
> 
> Can you upload the IR of relevance?

Bringing @davidedelvento into the conversation for this, as this would be a decision on his end.

I _believe_ I've reproduced the issue in a similar way by replicating the original code structure until the error appears. I've pasted the source code, Makefile, and the IR output at each stage in this gist: [https://gist.github.com/RasmitDevkota/125e7a2ab0dce086854b39f8bf4a0b13](https://gist.github.com/RasmitDevkota/125e7a2ab0dce086854b39f8bf4a0b13). The original code contains more structure than this minimal snippet, but when I add the additional complexity, it doesn't seem to change the issue at all, so I've kept this example as simple as possible.

In particular, looking at `debug_opt.ll`, we see that there is stack-allocated memory (line 804):
```llvm
  %"malloccall'mi" = alloca i8, i64 %mallocsize74, align 16
```
which is freed in another block (line 589):
```llvm
  call void @free(ptr nonnull %"malloccall'mi")
```

Running the program with GDB and printing the backtrace results in the output below
```
calculating objective function value
calculating objective function gradient
munmap_chunk(): invalid pointer

Program received signal SIGABRT, Aborted.
0x00007ffff7e4ae44 in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7e4ae44 in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff7df2a30 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff7dda4c3 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff7ddb354 in ?? () from /usr/lib/libc.so.6
#4  0x00007ffff7e55085 in ?? () from /usr/lib/libc.so.6
#5  0x00007ffff7e5531c in ?? () from /usr/lib/libc.so.6
#6  0x00007ffff7e59dfa in free () from /usr/lib/libc.so.6
#7  0x0000555555555d83 in calc (n=<optimized out>, x=<optimized out>) at main.c:24
#8  0x0000555555555840 in obj (n=12, grad=0x55555555a2a0, x=<optimized out>, my_func_data=<optimized out>) at main.c:46
#9  main () at main.c:68
```
One noticeable (but maybe not significant) difference in this case is that the error message doesn't vary as much as with the original code, though I suspect that has to do with the varying amount of optimization available in either case.

**Comment by wsmoses** [comment]
should be resolved by https://github.com/EnzymeAD/Enzyme/pull/2055

**Comment by davidedelvento** [comment]
Working on a (small) reproducer, which is hard to create. Will post a separate github issue when I succeed with said reproducer.
